[package]
name = "slog-json"
version = "2.6.1"
edition = "2018"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "JSON drain for slog-rs"
keywords = ["slog", "logging", "json"]
license = "MPL-2.0 OR MIT OR Apache-2.0"
documentation = "https://docs.rs/slog-json"
homepage = "https://github.com/slog-rs/slog"
repository = "https://github.com/slog-rs/json"
readme = "README.md"
# This is our Minimum Supported Rust Version (MSRV)
#
# Please do not bump this unnecessarily.
# Changing this should bump the minor version for semver (2.x for semver).
#
# This currently matches the MSRV of slog
rust-version = "1.61"

[features]
default = ["nested-values"]
nested-values = ["dep:erased-serde", "slog/nested-values"]
dynamic-keys = ["slog/dynamic-keys"]

[dependencies]
slog = "2.8"
serde_json = "1"
serde = "1"
erased-serde = { version = "0.4", optional = true }
time = { version = "0.3.6", features = ["formatting"] }

[dev-dependencies]
slog-async = "2"

[package.metadata.docs.rs]
features = ["dynamic-keys"]
